### ISSUE TITLE
Error Handling with empty file list

### ISSUE THREAD

**Issue by hypery2k** [larscheid-schmitzhermes/keycloak-monitoring-prometheus#14]
Seeing this error multiple times in our server looks
```
14:32:44,555 ERROR [org.keycloak.events.EventBuilder] (default task-587) Failed to send type to com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider@5de6f2b0: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at deployment.keycloak-monitoring-prometheus.jar//com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider.increaseCounter(MonitoringEventListenerProvider.java:96)
	at deployment.keycloak-monitoring-prometheus.jar//com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider.onEvent(MonitoringEventListenerProvider.java:34)
	at org.keycloak.keycloak-server-spi-private@9.0.0//org.keycloak.events.EventBuilder.send(EventBuilder.java:192)
	at org.keycloak.keycloak-server-spi-private@9.0.0//org.keycloak.events.EventBuilder.success(EventBuilder.java:157)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.services.managers.AuthenticationManager.finishedRequiredActions(AuthenticationManager.java:900)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticationComplete(AuthenticationProcessor.java:1099)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:862)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:150)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:465)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:160)
	at org.keycloak.keycloak-services@9.0.0//org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:111)
	at jdk.internal.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)

```

**Comment by hypery2k** [comment]
BTW: is there a particular reason to throw a RuntimeException here: 
https://github.com/larscheid-schmitzhermes/keycloak-monitoring-prometheus/blob/74a95760ac8589cd0099fe02a87d207fc675a7ab/src/main/java/com/larscheidschmitzhermes/keycloak/events/MonitoringEventListenerProvider.java#L99-L102

**Comment by tobilarscheid** [comment]
Hi Martin, as always: good catch! Thanks for giving back to the community here.

Regarding your question:
> BTW: is there a particular reason to throw a RuntimeException here:

If writing to the file fails, there is really no way to safely recover - that's why we bubble up the checked `IOException` as a `RuntimeException`
