### ISSUE TITLE
Failed to send type to com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider

### ISSUE THREAD

**Issue by cauwulixuan** [larscheid-schmitzhermes/keycloak-monitoring-prometheus#4]
Hi, I try to install keycloak-monitoring-prometheus followed by your setup step by step, but no data in my directory. and from logs, something was wrong, I am not familier with keycloak, so can someone help me figure it out?  Thank you.
logs here:
```
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider.getOrCreateCounterFile(MonitoringEventListenerProvider.java:75)
        ... 68 more

2018-02-01 12:23:49,931 ERROR [org.keycloak.events.EventBuilder] (default task-9) Failed to send type to com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider@21461b15: java.lang.RuntimeException: java.io.IOException: No such file or directory
        at com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider.getOrCreateCounterFile(MonitoringEventListenerProvider.java:78)
        at com.larscheidschmitzhermes.keycloak.events.MonitoringEventListenerProvider.onEvent(MonitoringEventListenerProvider.java:32)
        at org.keycloak.events.EventBuilder.send(EventBuilder.java:187)
        at org.keycloak.events.EventBuilder.success(EventBuilder.java:156)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.codeToToken(TokenEndpoint.java:385)
        at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)

```

**Comment by tobilarscheid** [comment]
Please make sure your configured events directory exists!
